name: dimplom
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.1.6
  email_validator: ^2.0.1
  carousel_slider: ^4.1.1
  video_player: ^2.4.4
  chewie: ^1.3.3
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.3
  lottie: ^1.3.0
  dio: ^5.4.3+1
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  shimmer: ^2.0.0
  youtube_player_flutter: ^8.0.0
  webview_flutter: ^3.0.4
  file_picker: ^4.6.1
  url_launcher: ^6.1.4
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.15
  http: ^0.13.4
  percent_indicator: ^4.0.1
  path_provider: ^2.0.11
  open_file: ^3.2.1
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^2.0.9
  pdf: ^3.10.8
  flutterfire_cli: ^1.0.0
  firebase_core: ^2.30.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  url_launcher_windows: ^3.1.1
  equatable: ^2.0.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.9
  firebase_database: ^10.5.5
  hive_cache_interceptor: ^1.0.0-dev.4
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/
    - assets/banner/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
