// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );[[[[[[[[]]]]]]]]
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRzDpbb01R5k1gucmq81a4zIA3uQEVjLo',
    appId: '1:18043779408:web:05fd5f09fd8bbda9169455',
    messagingSenderId: '18043779408',
    projectId: 'diplom-1-6bbaf',
    authDomain: 'diplom-1-6bbaf.firebaseapp.com',
    storageBucket: 'diplom-1-6bbaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClu1TAmjGG5ePNCUhHvEML3qD1WA3fFyI',
    appId: '1:18043779408:android:55e81c05c6cca271169455',
    messagingSenderId: '18043779408',
    projectId: 'diplom-1-6bbaf',
    storageBucket: 'diplom-1-6bbaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtscsWvcEptqYCZIAAlWoTnVXmaYSsnuY',
    appId: '1:18043779408:ios:24bce3c679b6e843169455',
    messagingSenderId: '18043779408',
    projectId: 'diplom-1-6bbaf',
    storageBucket: 'diplom-1-6bbaf.appspot.com',
    iosBundleId: 'com.example.dimplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtscsWvcEptqYCZIAAlWoTnVXmaYSsnuY',
    appId: '1:18043779408:ios:24bce3c679b6e843169455',
    messagingSenderId: '18043779408',
    projectId: 'diplom-1-6bbaf',
    storageBucket: 'diplom-1-6bbaf.appspot.com',
    iosBundleId: 'com.example.dimplom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRzDpbb01R5k1gucmq81a4zIA3uQEVjLo',
    appId: '1:18043779408:web:b0a5a0a466f5df1e169455',
    messagingSenderId: '18043779408',
    projectId: 'diplom-1-6bbaf',
    authDomain: 'diplom-1-6bbaf.firebaseapp.com',
    storageBucket: 'diplom-1-6bbaf.appspot.com',
  );

}